# DESCRIPTION: Travis-CI config
#
# Copyright 2003-2019 by Todd Strader. Verilator is free software; you can
# redistribute it and/or modify it under the terms of either the GNU Lesser
# General Public License Version 3 or the Perl Artistic License Version 2.0.

version: ~> 1.0

language: cpp

os: linux
dist: focal
compiler: gcc

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - VERILATOR_ROOT=$TRAVIS_BUILD_DIR/submodules/verilator

stages:
  - build
  - test

before_install:
  - cd "$TRAVIS_BUILD_DIR" # Skipping the git clone in later stages requires this
  - | # Update the verilator submodule here to pick up CI scripts
    if [ "$TRAVIS_BUILD_STAGE_NAME" = "build" ]; then
      git submodule update --remote --merge $VERILATOR_ROOT
    fi
  - export CCACHE_MAXSIZE=$($VERILATOR_ROOT/ci/travis-ccache-size.bash)
  - env | sort
  - g++ -E -dM -c -x c++ /dev/null | sort

install:
  - $VERILATOR_ROOT/ci/travis-install.bash

before_script:
  - $VERILATOR_ROOT/ci/travis-ccache-maint.bash

before_cache:
  - ccache -s -z

jobs:
  include:
    - stage: build
      script: |
              # Compile verilator
              pushd $VERILATOR_ROOT
              autoconf
              ./configure --enable-ccwarn
              make -j $(nproc)
              popd
      workspaces: {create: {name: build, paths: .}}
    - stage: test
      workspaces: {use: build}
      git: {clone: false}
      script: make test

after_script:
  - git submodule status

notifications:
  email:
    if: repo = verilator/verilator_ext_tests
    recipients:
      - wsnyder@wsnyder.org
      - todd.strader@gmail.com
